"""OpenWrt: add capabilities and communication protocol

Revision ID: a59b23b319f1
Revises: 23bd2ccb7ac0
Create Date: 2017-05-18 14:22:55.616114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59b23b319f1'
down_revision = '23bd2ccb7ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openwrt', sa.Column('capabilities', sa.Text(), nullable=True))
    op.add_column('openwrt', sa.Column('communication_protocol', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openwrt', 'communication_protocol')
    op.drop_column('openwrt', 'capabilities')
    # ### end Alembic commands ###
